sudo: required

language: generic

services:
   - docker

before_install:
   - docker build -t manojsilag/docker_react -f Dockerfile.dev .

script:
   - docker run -e CI=true manojsilag/docker_react npm run test -- --coverage